version: "3.9"
services:
  postgres:
    container_name: postgresql
    restart: always
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
